auto: true

markdown: rdiscount

highlighter: 'pygments'
#paginate: 8
permalink: /:title

name: “张云峰的博客”
title: 张云峰的博客
description: 文青，程序猿，技术宅
url: http://www.zhangyunfeng.bid
feed: /atom.xml
author_info: <a href="http://www.zhangyunfeng.bid/">zhangyunfeng</a>

intensedebate_comments: true